server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    location / { try_files $uri $uri/ /index.html; }
    location /api/trade-capture/ { proxy_pass http://trade-capture-service:8080/api/; }
    location /api/pnl-risk/ { proxy_pass http://pnl-risk-consumer:8081/api/; }
    gzip on;
    gzip_types text/css application/javascript application/json;
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
}
